version: "3.9"
services:
  redis:
    image: redis:latest
    expose:
      - "6379:6379"
    command: "redis-server --save 20 1 --requirepass ${DATABASE_PASSWORD}"
    volumes:
      - redis:/data
    restart: always
  mariadb:
    image: mariadb:latest
    expose:
      - "3306:3306"
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MARIADB_ROOT_HOST=localhost"
      - "MARIADB_DATABASE=scholarsome"
      - "MARIADB_USER=scholarsome"
      - "MARIADB_PASSWORD=${DATABASE_PASSWORD}"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  scholarsome:
    image: hwgilbert16/scholarsome:latest
    platform: "linux/amd64"
    ports:
      - "${HTTP_PORT}:8080"
    env_file:
      - ".env"
    environment:
      - "DATABASE_URL=mysql://scholarsome:${DATABASE_PASSWORD}@mariadb:3306/scholarsome"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_USERNAME="
      - "STORAGE_LOCAL_DIR=/data"
    volumes:
      - scholarsome:/data
    depends_on:
      - mariadb
      - redis
    restart: always
volumes:
  redis:
    driver: local
  mariadb:
  scholarsome:
